name: Build Redis
run-name: Build Redis ${{ inputs.redis_version }} (${{ inputs.release_type }})

on:
  workflow_dispatch:
    inputs:
      redis_version:
        description: 'Redis version to build'
        required: true
        default: '6.2.16'
        type: string
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - stable
          - beta
          - alpha
        default: 'stable'
      build_note:
        description: 'Additional build notes'
        required: false
        type: string
        default: ''

env:
  INSTALL_PREFIX: /usr/local
  ARTIFACT_DIR: artifacts

jobs:
  build:
    # name: Build Redis
    name: jobs Build Redis ${{ inputs.redis_version }} (${{ inputs.release_type }})
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9

    steps:
      - name: Install build dependencies
        run: |
          dnf update -y
          dnf group install -y "Development Tools"
          dnf install -y \
            wget \
            gcc \
            make \
            tar \
            gzip \
            systemd-devel

      - name: Download Redis source
        run: |
          wget https://download.redis.io/releases/redis-${{ inputs.redis_version }}.tar.gz
          tar xzf redis-${{ inputs.redis_version }}.tar.gz

      - name: Build Redis
        run: |
          cd redis-${{ inputs.redis_version }}
          make MALLOC=libc \
            PREFIX=${{ env.INSTALL_PREFIX }} \
            USE_SYSTEMD=yes \
            -j$(nproc)

      - name: Install Redis
        run: |
          cd redis-${{ inputs.redis_version }}
          make install PREFIX=${{ env.INSTALL_PREFIX }}

      - name: Prepare artifacts
        id: prepare
        run: |
          mkdir -p ${{ env.ARTIFACT_DIR }}
          # Copy binaries and config files
          cp ${{ env.INSTALL_PREFIX }}/bin/redis* ${{ env.ARTIFACT_DIR }}/
          cp redis-${{ inputs.redis_version }}/redis.conf ${{ env.ARTIFACT_DIR }}/

          # Create detailed build info
          cat > ${{ env.ARTIFACT_DIR }}/build-info.txt << EOF
          Build Information:
          -----------------
          Redis Version: ${{ inputs.redis_version }}
          Release Type: ${{ inputs.release_type }}
          Build Date: $(date)
          Build System: Rocky Linux 9 (x86_64)
          Build Notes: ${{ inputs.build_note }}

          Compiler Version: $(gcc --version | head -n1)
          Make Version: $(make --version | head -n1)

          Build Configuration:
          - MALLOC: libc
          - PREFIX: ${{ env.INSTALL_PREFIX }}
          - USE_SYSTEMD: yes
          EOF

          # Calculate SHA256 checksum for binaries
          cd ${{ env.ARTIFACT_DIR }}
          sha256sum redis-* > sha256sums.txt

          # Create artifact package
          ARTIFACT_NAME="redis-${{ inputs.redis_version }}-rockylinux9-x86_64.tar.gz"
          cd ..
          tar czf $ARTIFACT_NAME -C ${{ env.ARTIFACT_DIR }} .
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT

          # Generate SHA256 for the final package
          sha256sum $ARTIFACT_NAME > ${ARTIFACT_NAME}.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: redis-build
          path: |
            redis-${{ inputs.redis_version }}-rockylinux9-x86_64.tar.gz
            redis-${{ inputs.redis_version }}-rockylinux9-x86_64.tar.gz.sha256

    outputs:
      artifact_name: ${{ steps.prepare.outputs.artifact_name }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: redis-build
          path: ./

      - name: Generate changelog
        run: |
          cat > changelog.md << EOF
          # Redis ${{ inputs.redis_version }} for Rocky Linux 9 (x86_64)

          ## Build Information
          - **Version:** ${{ inputs.redis_version }}
          - **Release Type:** ${{ inputs.release_type }}
          - **Build Date:** $(date)
          - **Platform:** Rocky Linux 9 (x86_64)

          ## Build Notes
          ${BUILD_NOTES:-No additional notes}

          ## SHA256 Checksums
          \`\`\`
          $(cat redis-${{ inputs.redis_version }}-rockylinux9-x86_64.tar.gz.sha256)
          \`\`\`

          ## Installation
          1. Download the package
          2. Verify the checksum:
             \`sha256sum -c redis-${{ inputs.redis_version }}-rockylinux9-x86_64.tar.gz.sha256\`
          3. Extract the archive:
             \`tar xzf redis-${{ inputs.redis_version }}-rockylinux9-x86_64.tar.gz\`

          ## Additional Information
          - Workflow Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          - Build Trigger: Manual by @${{ github.actor }}
          EOF
        env:
          BUILD_NOTES: ${{ inputs.build_note }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: redis-${{ inputs.redis_version }}-rockylinux9
          name: Redis ${{ inputs.redis_version }} (${{ inputs.release_type }}) - Rocky Linux 9
          body_path: changelog.md
          draft: false
          prerelease: ${{ inputs.release_type != 'stable' }}
          files: |
            redis-${{ inputs.redis_version }}-rockylinux9-x86_64.tar.gz
            redis-${{ inputs.redis_version }}-rockylinux9-x86_64.tar.gz.sha256
