name: Build Redis

on:
  workflow_dispatch:
    inputs:
      redis_version:
        description: 'Redis version to build'
        required: true
        default: '7.2.3'
        type: string
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - stable
          - beta
          - alpha
        default: 'stable'

env:
  INSTALL_PREFIX: /usr/local
  ARTIFACT_DIR: artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9

    steps:
      # Install necessary build tools and dependencies
      - name: Install build dependencies
        run: |
          dnf update -y
          dnf group install -y "Development Tools"
          dnf install -y \
            wget \
            gcc \
            make \
            tar \
            gzip \
            systemd-devel

      # Download and extract Redis source code
      - name: Download Redis source
        run: |
          wget https://download.redis.io/releases/redis-${{ inputs.redis_version }}.tar.gz
          tar xzf redis-${{ inputs.redis_version }}.tar.gz

      # Build Redis with specified options
      - name: Build Redis
        run: |
          cd redis-${{ inputs.redis_version }}
          make MALLOC=libc \
            PREFIX=${{ env.INSTALL_PREFIX }} \
            USE_SYSTEMD=yes \
            -j$(nproc)

      # Install Redis to the specified prefix
      - name: Install Redis
        run: |
          cd redis-${{ inputs.redis_version }}
          make install PREFIX=${{ env.INSTALL_PREFIX }}

      # Prepare and package artifacts
      - name: Prepare artifacts
        id: prepare
        run: |
          mkdir -p ${{ env.ARTIFACT_DIR }}
          # Copy binaries and config files
          cp ${{ env.INSTALL_PREFIX }}/bin/redis* ${{ env.ARTIFACT_DIR }}/
          cp redis-${{ inputs.redis_version }}/redis.conf ${{ env.ARTIFACT_DIR }}/

          # Create version info file
          echo "Redis version: ${{ inputs.redis_version }}" > ${{ env.ARTIFACT_DIR }}/version.txt
          echo "Build date: $(date)" >> ${{ env.ARTIFACT_DIR }}/version.txt

          # Create artifact package
          ARTIFACT_NAME="redis-${{ inputs.redis_version }}-rockylinux9-x86_64.tar.gz"
          tar czf $ARTIFACT_NAME -C ${{ env.ARTIFACT_DIR }} .
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT

      # Upload artifact for the release job
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: redis-build
          path: redis-${{ inputs.redis_version }}-rockylinux9-x86_64.tar.gz
          retention-days: 1

    outputs:
      artifact_name: ${{ steps.prepare.outputs.artifact_name }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Download the artifact from previous job
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: redis-build
          path: ./

      # Generate release changelog
      - name: Generate changelog
        run: |
          echo "Redis ${{ inputs.redis_version }} built for Rocky Linux 9 (x86_64)" > changelog.md
          echo "Build type: ${{ inputs.release_type }}" >> changelog.md
          echo "Build date: $(date)" >> changelog.md

      # Create GitHub release and upload artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: redis-${{ inputs.redis_version }}-rockylinux9
          name: Redis ${{ inputs.redis_version }} (Rocky Linux 9)
          body_path: changelog.md
          draft: false
          prerelease: ${{ inputs.release_type != 'stable' }}
          files: ${{ needs.build.outputs.artifact_name }}
