name: Build Redis

on:
  workflow_dispatch:
    inputs:
      redis_version:
        description: 'Redis version to build'
        required: true
        default: '7.2.3'
        type: string
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - stable
          - beta
          - alpha
        default: 'stable'

env:
  INSTALL_PREFIX: /usr/local
  ARTIFACT_DIR: artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9

    steps:
      - name: Install build dependencies
        run: |
          dnf update -y
          dnf group install -y "Development Tools"
          dnf install -y \
            wget \
            gcc \
            make \
            tar \
            gzip \
            systemd-devel

      - name: Download Redis source
        run: |
          wget https://download.redis.io/releases/redis-${{ inputs.redis_version }}.tar.gz
          tar xzf redis-${{ inputs.redis_version }}.tar.gz

      - name: Build Redis
        run: |
          cd redis-${{ inputs.redis_version }}
          make MALLOC=libc \
            PREFIX=${{ env.INSTALL_PREFIX }} \
            USE_SYSTEMD=yes \
            -j$(nproc)

      - name: Install Redis
        run: |
          cd redis-${{ inputs.redis_version }}
          make install PREFIX=${{ env.INSTALL_PREFIX }}

      - name: Prepare artifacts
        run: |
          mkdir -p ${{ env.ARTIFACT_DIR }}

          cp ${{ env.INSTALL_PREFIX }}/bin/redis* ${{ env.ARTIFACT_DIR }}/
          cp redis-${{ inputs.redis_version }}/redis.conf ${{ env.ARTIFACT_DIR }}/

          echo "Redis version: ${{ inputs.redis_version }}" > ${{ env.ARTIFACT_DIR }}/version.txt
          echo "Build date: $(date)" >> ${{ env.ARTIFACT_DIR }}/version.txt

          tar czf redis-${{ inputs.redis_version }}-rockylinux9-x86_64.tar.gz -C ${{ env.ARTIFACT_DIR }} .

      - name: Save artifact to workspace
        run: |
          mkdir -p /github/workspace/
          cp redis-${{ inputs.redis_version }}-rockylinux9-x86_64.tar.gz /github/workspace/

    outputs:
      artifact_name: redis-${{ inputs.redis_version }}-rockylinux9-x86_64.tar.gz

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact from workspace
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: ./

      - name: Generate changelog
        run: |
          echo "Redis ${{ inputs.redis_version }} built for Rocky Linux 9 (x86_64)" > changelog.md
          echo "Build type: ${{ inputs.release_type }}" >> changelog.md
          echo "Build date: $(date)" >> changelog.md

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: redis-${{ inputs.redis_version }}-rockylinux9
          name: Redis ${{ inputs.redis_version }} (Rocky Linux 9)
          body_path: changelog.md
          draft: false
          prerelease: ${{ inputs.release_type != 'stable' }}
          files: |
            ${{ needs.build.outputs.artifact_name }}
